# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Compiling and Testing iOS App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Xcode
      uses: actions/setup-xcode@v2
      with:
        xcode-version: '12.x' # Adjust the Xcode version as needed
    - name: Build and Test
      run: |
        xcodebuild clean test -workspace "Expense Tracker.xcworkspace" -scheme "Expense Tracker" -destination "platform=iOS Simulator,name=iPhone 12" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO | xcpretty
